version: '3.9'

services:
  huddle-admin-service:
    container_name: huddle-admin-service
    image: subashkj005/huddle-dating:admin-service
    ports:
      - "8931:8931"

  huddle-zookeeper:
    container_name: huddle-zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  huddle-kafka:
    container_name: huddle-kafka
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=huddle-zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://huddle-kafka:9092,EXTERNAL://35.223.178.123:9093 
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - huddle-zookeeper

  huddle-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: huddle-kafka-ui
    ports:
      - "18080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=huddle-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=huddle-zookeeper:2181
    depends_on:
      - huddle-kafka
      - huddle-zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local